import React from 'react';
import { 
  LayoutDashboard, 
  Megaphone, 
  BarChart3, 
  Settings, 
  Plus, 
  Search, 
  Bell, 
  User, 
  Sparkles,
  ArrowUpRight,
  ArrowDownRight,
  CheckCircle,
  PauseCircle,
  MousePointer2,
  Eye,
  DollarSign,
  Edit,
  Users,
  Image,
  MessageSquare,
  Send,
  Upload,
  Wand2,
  Video,
  Globe,
  Copy,
  Clock,
  Calendar,
  Menu,
  X,
  ChevronLeft
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Campaigns: Megaphone,
  Reports: BarChart3,
  Settings: Settings,
  Plus: Plus,
  Search: Search,
  Bell: Bell,
  User: User,
  AI: Sparkles,
  TrendUp: ArrowUpRight,
  TrendDown: ArrowDownRight,
  Active: CheckCircle,
  Paused: PauseCircle,
  Click: MousePointer2,
  Impression: Eye,
  Cost: DollarSign,
  Edit: Edit,
  Audiences: Users,
  Assets: Image,
  Chat: MessageSquare,
  Send: Send,
  Upload: Upload,
  Studio: Wand2,
  Video: Video,
  Globe: Globe,
  Copy: Copy,
  Clock: Clock,
  Calendar: Calendar,
  Menu: Menu,
  X: X,
  Back: ChevronLeft
};